version: "3.9"

services:
  db:
    image: postgres:15
    container_name: carapp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carapp
    ports:
      - "5432:5432"
  
  backend:
  build: .
  container_name: carapp_backend
  depends_on:
    - db
  environment:
    DATABASE_URL: postgresql://postgres:password@db:5432/carapp
  ports:
    - "8000:8000"